service: sls-seed
frameworkVersion: "3"

custom:
  tableName: "my-table"
  dynamodb:
    stages:
      - dev
      - prod
    start:
      migrate: true

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    MY_TABLE: ${self:custom.tableName}

functions:
  api:
    handler: index.test
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-typescript
  - serverless-dynamodb
  - serverless-offline
